use axum::extract::State;
use http::StatusCode;
use crate::database::structs;
use crate::database::utils::introspect_table::load_table_specs;
use crate::AppState;

pub async fn get_typedefs(
    State(state): State<AppState>,
) -> Result<String, StatusCode> {
    let mut output = String::new();

    output.push_str("// AUTO-GENERATED BY ToastyRabbit\n");
    output.push_str("// Do not edit by hand.\n\n");

    output.push_str("declare module \"toastyrabbit/datatypes\" {\n");

    let tables = load_table_specs(&state.db).await.unwrap();
    let len = tables.len();

    for (i, table) in tables.clone().into_iter().enumerate() {
        let interface_name = to_pascal_case(&table.table);

        output.push_str(&format!("  export interface {} {{\n", interface_name));
        for (col_name, kind) in &table.columns {
            let ts_type = column_kind_to_ts(*kind);
            output.push_str(&format!("    {}: {};\n", col_name, ts_type));
        }

        output.push_str("  }\n");

        if i + 1 != len {
            output.push('\n');
        }
    }

    output.push_str("\n  export interface ToastyTables {\n");
    for table in tables.iter() {
        let interface_name = to_pascal_case(&table.table);
        output.push_str(&format!("    {}: {};\n", table.table, interface_name));
    }
    output.push_str("  }\n");

    output.push_str("}\n");

    Ok(output)
}

fn column_kind_to_ts(kind: structs::ColumnKind) -> &'static str {
    match kind {
        structs::ColumnKind::Id => "number",
        structs::ColumnKind::Number => "number",
        structs::ColumnKind::DateTime => "Date",
        structs::ColumnKind::String => "string",
        structs::ColumnKind::Boolean => "boolean",
    }
}

fn to_pascal_case(name: &str) -> String {
    // "users" -> "Users", "payment_items" -> "PaymentItems"
    name.split('_')
        .filter(|s| !s.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
    None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}
