// AUTO-GENERATED BY ToastyRabbit
// Do not edit by hand.

declare module "toastyrabbit/datatypes" {
  export interface Users {
    created_at: Date;
    id: number;
    name: string;
  }

  export interface Payments {
    amount: number;
    created_at: Date;
    id: number;
    is_paid: boolean;
    name: string;
  }

  export interface ToastyTables {
    users: Users;
    payments: Payments;
  }
}
