// AUTO-GENERATED BY ToastyRabbit
// Do not edit by hand.

declare module "toastyrabbit/datatypes" {
  export interface Users {
    created_at: Date;
    id: number;
    name: string;
  }

  export interface Payments {
    amount: number;
    created_at: Date;
    id: number;
    is_paid: boolean;
    name: string;
  }

  export interface SomeTableTest123 {
    id: number;
    some_column: string;
    some_date: Date;
    test_string: string;
  }

  export interface ToastyTables {
    users: Users;
    payments: Payments;
    some_table_test_123: SomeTableTest123;
  }

  export type TT = ToastyTables;
}
